### ISSUE TITLE
Location eg. G/Gre

### ISSUE THREAD

**Issue by ubriquejazz** [imoren2x/django_polska_biblioteka#12]
Hola Nacho!

Could you just leave 'category' to be shown without 'location', please?
Location should be visible for admins only. 

Still the surname is shown as the 2nd. The name should be on the 2nd place.
Could you change it, please? 

And I think it would be better if the patter for: Publisher, City of publishing and date, was as below.
eg. Czytelnik, Warsaw 1992

Could you consider this, please?

Dorota

**Comment by ubriquejazz** [comment]
Submitted change 64ac0d415f1b90c4b07a68ae284299c175d96b69

**Comment by imoren2x** [comment]
This request has been **accepted** and **accomplished**, then it can be closed.

I attach this screenshot as evidence of completion of the request:

![image](https://user-images.githubusercontent.com/35999100/97802019-e4f9e880-1c40-11eb-853b-55b8f5f3a3cc.png)


In case there is any complain or the request has not been completed, please **re-open** it again.
